### ISSUE TITLE
Canvas2ImageDemo.js Not found

### ISSUE THREAD

**Issue by fkamlesh** [devgeeks/Canvas2ImageDemo#3]
Please add Canvas2ImageDemo.js

**Comment by devgeeks** [comment]
`Canvas2ImageDemo.js` is a build artefact. It is generated by running `npm run build-js`

However, there is no source in `Canvas2ImageDemo.js` that isn't just in [the src folder](https://github.com/devgeeks/Canvas2ImageDemo/tree/master/src)
